import { TrinketItem } from '@/types';

export const BANNER_TRINKETS: TrinketItem[] = [
  {
    image: '/trinkets/trinket.webp',
    defaultTop: [70, 69],
    defaultLeft: [15, 12.5],
    size: 0.3375,
    rotate: 0,
    mobile: true,
  },
  {
    image: '/trinkets/trinket-1.webp',
    defaultTop: [76, 0],
    defaultLeft: [44, 0],
    size: 0.225,
    rotate: -30,
    mobile: false,
  },
  {
    image: '/trinkets/trinket-2.webp',
    defaultTop: [75, 0],
    defaultLeft: [48, 0],
    size: 0.225,
    rotate: 0,
    mobile: false,
  },
  {
    image: '/trinkets/trinket-3.webp',
    defaultTop: [78, 0],
    defaultLeft: [52, 0],
    size: 0.225,
    rotate: 30,
    mobile: false,
  },
  {
    image: '/trinkets/trinket-4.webp',
    defaultTop: [35, 50],
    defaultLeft: [17, 12],
    size: 0.3,
    rotate: 0,
    mobile: true,
  },
  {
    image: '/trinkets/trinket-5.webp',
    defaultTop: [24, 32.5],
    defaultLeft: [47.5, 50],
    size: 0.3,
    rotate: 0,
    mobile: true,
  },
  {
    image: '/trinkets/trinket-6.webp',
    defaultTop: [55, 52],
    defaultLeft: [67, 90],
    size: 0.2125,
    rotate: 20,
    mobile: true,
  },
  {
    image: '/trinkets/trinket-7.webp',
    defaultTop: [67.5, 71],
    defaultLeft: [84, 82],
    size: 0.375,
    rotate: 10,
    mobile: true,
  },
  {
    image: '/trinkets/trinket-8.webp',
    defaultTop: [50, 32],
    defaultLeft: [28.5, 30],
    size: 0.2,
    rotate: 0,
    mobile: true,
  },
  {
    image: '/trinkets/trinket-10.webp',
    defaultTop: [27, 35],
    defaultLeft: [62, 70],
    size: 0.225,
    rotate: 0,
    mobile: true,
  },
  {
    image: '/trinkets/trinket-13.webp',
    defaultTop: [80, 63],
    defaultLeft: [65, 51],
    size: 0.3,
    rotate: 10,
    mobile: true,
  },
  {
    image: '/trinkets/trinket-14.webp',
    defaultTop: [82, 75],
    defaultLeft: [31, 45],
    size: 0.3,
    rotate: 30,
    mobile: true,
  },
  {
    image: '/trinkets/trinket-15.webp',
    defaultTop: [22, 0],
    defaultLeft: [35, 0],
    size: 0.225,
    rotate: 10,
    mobile: false,
  },
  {
    image: '/trinkets/trinket-16.webp',
    defaultTop: [27, 38],
    defaultLeft: [77, 92],
    size: 0.3,
    rotate: -15,
    mobile: true,
  },
  {
    image: '/trinkets/trinket-17.webp',
    defaultTop: [52, 35],
    defaultLeft: [37, 12.5],
    size: 0.15,
    rotate: 0,
    mobile: true,
  },
];
