import { WorkContent } from '@/types';

export const WORK_PAGES: WorkContent[] = [
  {
    id: 'huddle01',
    about:
      'The decentralized cloud for real-time connectivity delivering unmatched speed, security and scalability. Powered by the people. Built for startups and enterprises.',
    industry: ['DePIN', 'Blockchain', 'Audio/Video', 'Gaming'],
    metrics: ['300K+ Community Members', '20+ Media & PR Mentions', '5M+ Impressions yearly'],
    role: [
      'Creative Direction',
      'Brand Positioning',
      'Campaign Planning',
      'Social Media',
      'PR',
      'Community and Events',
    ],
    content: [
      '1st marketing leadership hire. Led the rebrand from zoom for web3 to DePIN for real-time connectivity.',
      'Defined distinct brand positioning, tone of voice, visual aesthetic, and community culture.',
      'Scaled socials from 4K → 175K on X, 2K → 200K on Discord, 0 → 90K+ on Telegram.',
      'Crafted campaigns for Testnet (2.95M txns), Node Sales (2.6K+ sold), Meet App (600M+ mins), FarHouse App Launch and more.',
      'Created branded lore, memes, merchandise, pepe mascot, and shitposts to drive community engagement.',
      'Drove co-marketing and PR for partnerships with Arbitrum, Celestia, Aethir, Caldera, etc.',
      'Secured media via Serotonin, Energent, and others across CoinDesk, The Defiant, Decrypt.',
      'Enabled 200+ creators with guides, assets, shoutouts, workshops, and lootboxes.',
      'Led marketing for flagship events like FILBangalore (3 years, 1300+ attendees/event, 1M+ social impressions) and secured other event opportunities for Huddle01 with ETHGlobal, Fluence, Aethir and Protocol Labs.',
      'Collaborated with the engineering team to create blogs, infographics, threads and long form educational content to build thought leadership and awareness',
    ],
    display: [
      '/posters/brand-strategy/huddle01/image.webp',
      '1777713415295049791',
      '/posters/brand-strategy/huddle01/image-1.webp',
      '/posters/brand-strategy/huddle01/image-2.webp',
      '/posters/brand-strategy/huddle01/image-3.webp',
      '/posters/brand-strategy/huddle01/image-4.webp',
      '1849429031231623421',
      '/posters/brand-strategy/huddle01/image-5.webp',
      '/posters/brand-strategy/huddle01/image-6.webp',
      '/posters/brand-strategy/huddle01/image-7.webp',
      '/posters/brand-strategy/huddle01/image-8.webp',
      '/posters/brand-strategy/huddle01/image-9.webp',
      '/posters/brand-strategy/huddle01/image-10.webp',
      '/posters/brand-strategy/huddle01/image-11.webp',
      '/posters/brand-strategy/huddle01/image-12.webp',
      '/posters/brand-strategy/huddle01/image-13.webp',
      '/posters/brand-strategy/huddle01/image-14.webp',
      '/posters/brand-strategy/huddle01/image-15.webp',
      '/posters/brand-strategy/huddle01/image-16.webp',
      '/posters/brand-strategy/huddle01/image-17.webp',
      '/posters/brand-strategy/huddle01/image-18.webp',
      '/posters/brand-strategy/huddle01/image-19.webp',
      '/posters/brand-strategy/huddle01/image-20.webp',
    ],
  },
  {
    id: 'fil-bangalore',
    about:
      "Huddle01's flagship 2-day conference style event in partnership with Filecoin. Hosted in Bangalore - India's tech hub and attracting 1300+ participants each year.",
    industry: ['Events'],
    role: ['Creative Direction', 'On-ground Coverage', 'Social Media', 'Email Marketing'],
    content: [
      'Collaborated with the Design team to create the FILBangalore brand - a blend of Indian roots with global FIL events aesthetics.',
      'Themed each edition with custom assets, merch, websites, installations & activations including an IRL treasure hunt.',
      'Managed speaker comms, giveaways, treasure hunts, email marketing (via Luma), and real-time coverage.',
    ],
    display: [
      '/posters/brand-strategy/fil-bangalore/image.webp',
      '/posters/brand-strategy/fil-bangalore/image-1.webp',
      '/posters/brand-strategy/fil-bangalore/image-2.webp',
      '/posters/brand-strategy/fil-bangalore/image-3.webp',
      '/posters/brand-strategy/fil-bangalore/image-4.webp',
      '1603079684509818880',
      '/posters/brand-strategy/fil-bangalore/image-5.webp',
      '/posters/brand-strategy/fil-bangalore/image-6.webp',
      '/posters/brand-strategy/fil-bangalore/image-7.webp',
      '/posters/brand-strategy/fil-bangalore/image-8.webp',
      '/posters/brand-strategy/fil-bangalore/image-9.webp',
      '/posters/brand-strategy/fil-bangalore/image-10.webp',
      '/posters/brand-strategy/fil-bangalore/image-11.webp',
      '/posters/brand-strategy/fil-bangalore/image-12.webp',
      '/posters/brand-strategy/fil-bangalore/image-13.webp',
      '1862161422136025323',
      '/posters/brand-strategy/fil-bangalore/image-14.webp',
      '/posters/brand-strategy/fil-bangalore/image-15.webp',
      '/posters/brand-strategy/fil-bangalore/image-16.webp',
      '/posters/brand-strategy/fil-bangalore/image-17.webp',
      '/posters/brand-strategy/fil-bangalore/image-18.webp',
    ],
  },
  {
    id: 'den',
    about: 'Den is an upcoming fan-vestment app that lets you back your favourite streamers.',
    industry: ['Streaming'],
    role: ['Creative Direction'],
    content: [
      'Built the brand moodboard, visual and verbal tone, vision statement, user personas and worked with a designer, Ragy to bring it to life.',
    ],
    display: [
      '/posters/brand-strategy/den/image.webp',
      '/posters/brand-strategy/den/image-1.webp',
      '/posters/brand-strategy/den/image-2.webp',
      '/posters/brand-strategy/den/image-3.webp',
      '/posters/brand-strategy/den/image-4.webp',
      '/posters/brand-strategy/den/image-5.webp',
    ],
  },
  {
    id: 'hudl-nexus',
    about:
      "Huddle01's official gamified testnet with a multi arena quest board featuring points and tasks across apps, content creation, games, and socials.",
    metrics: ['174K+ Users', '2.95M Transactions', '200K+ Community Members'],
    role: ['Campaign Strategy', 'Social Media'],
    content: [
      'Worked with the team on quest board design, KOL shortlisting and briefing, creator tasks, partner badges, weekly leaderboards, point structure and rewards.',
      'Restructured Discord to smoothly onboard the new influx of community members and created gamified roles, channels and exclusive events to boost daily engagement.',
      'Created and executed the launch strategy on social media with pre-launch shitposting, announcement video, livestream with Arbitrum, engagement content for sustenance, KOL & Partner alignment, active reply guy-ing and onboarding 10K+ users in under 24 hours.',
    ],
    display: [
      '/posters/campaign-strategy/hudl-testnet-nexus/image.webp',
      '/posters/campaign-strategy/hudl-testnet-nexus/image-1.webp',
      '/posters/campaign-strategy/hudl-testnet-nexus/image-2.webp',
      '/posters/campaign-strategy/hudl-testnet-nexus/image-3.webp',
      '/posters/campaign-strategy/hudl-testnet-nexus/image-19.webp',
      '/posters/campaign-strategy/hudl-testnet-nexus/image-4.webp',
      '/posters/campaign-strategy/hudl-testnet-nexus/image-5.webp',
      '/posters/campaign-strategy/hudl-testnet-nexus/image-6.webp',
      '/posters/campaign-strategy/hudl-testnet-nexus/image-7.webp',
      '/posters/campaign-strategy/hudl-testnet-nexus/image-8.webp',
      '/posters/campaign-strategy/hudl-testnet-nexus/image-9.webp',
      '/posters/campaign-strategy/hudl-testnet-nexus/image-10.webp',
      '/posters/campaign-strategy/hudl-testnet-nexus/image-12.webp',
      '/posters/campaign-strategy/hudl-testnet-nexus/image-13.webp',
      '/posters/campaign-strategy/hudl-testnet-nexus/image-14.webp',
      '/posters/campaign-strategy/hudl-testnet-nexus/image-11.webp',
      '/posters/campaign-strategy/hudl-testnet-nexus/image-15.webp',
      '/posters/campaign-strategy/hudl-testnet-nexus/image-16.webp',
      '/posters/campaign-strategy/hudl-testnet-nexus/image-17.webp',
      '/posters/campaign-strategy/hudl-testnet-nexus/image-18.webp',
    ],
  },
  {
    id: 'battle-of-open-realm',
    about:
      'Phase 2 of Huddle01 Node Sales where buyers can purchase Media Nodes and contribute their bandwidth & compute to support our DePIN and earn $HUDL',
    metrics: ['392 Nodes sold', 'Priced at $340 each'],
    role: ['Campaign Strategy', 'Social Media'],
    content: [
      'To attract new buyers, I gamified the Media Node NFT keys into action figure cards featuring 5 HUDL Army characters with different rarities and node operator rewards.',
      'Created and executed the launch strategy on social media with pre-launch shitposting, announcement video script, spaces with Arbitrum, Caldera and Celestia, engagement content for sustenance, KOL & Partner alignment, active reply guy-ing and user generated content.',
      'Wrote blogs, threads, guides and other pieces of long form content to generate awareness for network use cases and opportunities',
    ],
    display: [
      '/posters/campaign-strategy/battle-of-open-realm/image-1.webp',
      '1927722726065619445',
      '/posters/campaign-strategy/battle-of-open-realm/image-2.webp',
      '/posters/campaign-strategy/battle-of-open-realm/image-3.webp',
      '/posters/campaign-strategy/battle-of-open-realm/image-6.webp',
      '/posters/campaign-strategy/battle-of-open-realm/image.webp',
      '/posters/campaign-strategy/battle-of-open-realm/image-8.webp',
      '/posters/campaign-strategy/battle-of-open-realm/image-5.webp',
      '/posters/campaign-strategy/battle-of-open-realm/image-13.webp',
      '/posters/campaign-strategy/battle-of-open-realm/image-7.webp',
      '/posters/campaign-strategy/battle-of-open-realm/image-9.webp',
      '/posters/campaign-strategy/battle-of-open-realm/image-11.webp',
      '/posters/campaign-strategy/battle-of-open-realm/image-10.webp',
      '/posters/campaign-strategy/battle-of-open-realm/image-12.webp',
      '/posters/campaign-strategy/battle-of-open-realm/image-4.webp',
    ],
  },
  {
    id: 'hudl-node-sales',
    about:
      'First phase of Huddle01 Node Sales where buyers can purchase Media Nodes and contribute their bandwidth & compute to support our DePIN and earn $HUDL',
    role: ['Campaign Strategy', 'Social Media'],
    metrics: ['2200 Nodes sold', 'Priced at $340 each'],
    content: [
      'Worked with the design team to help visualize the Media Node, create landing page, eli5 comic and infographics for awareness.',
      'Created and executed the launch strategy on social media with pre-launch shitposting, announcement video, L3 announcement with Arbitrum & Caldera, Global AMA series with Pukecast , engagement content for sustenance, FAQs, KOL & Partner alignment, active reply guy-ing and user generated content.',
      'Wrote blogs, threads, guides and other pieces of long form content to generate awareness around media nodes - its rewards and use cases.',
      'Restructured Discord to smoothly onboard Pioneers - our first set of Network Builders with exclusive channels, quests and events.',
      'Worked alongside Serotonin to secure a PR opportunity in CoinDesk.',
    ],
    display: [
      '/posters/campaign-strategy/hudl-node-sales/image.webp',
      '/posters/campaign-strategy/hudl-node-sales/image-1.webp',
      '/posters/campaign-strategy/hudl-node-sales/image-2.webp',
      '/posters/campaign-strategy/hudl-node-sales/image-3.webp',
      '/posters/campaign-strategy/hudl-node-sales/image-4.webp',
      '/posters/campaign-strategy/hudl-node-sales/image-5.webp',
      '1812878778479116743',
      '/posters/campaign-strategy/hudl-node-sales/image-6.webp',
      '/posters/campaign-strategy/hudl-node-sales/image-7.webp',
      '/posters/campaign-strategy/hudl-node-sales/image-8.webp',
      '/posters/campaign-strategy/hudl-node-sales/image-9.webp',
      '/posters/campaign-strategy/hudl-node-sales/image-10.webp',
      '/posters/campaign-strategy/hudl-node-sales/image-11.webp',
      '/posters/campaign-strategy/hudl-node-sales/image-12.webp',
      '/posters/campaign-strategy/hudl-node-sales/image-13.webp',
      '/posters/campaign-strategy/hudl-node-sales/image-14.webp',
      '/posters/campaign-strategy/hudl-node-sales/image-15.webp',
      '/posters/campaign-strategy/hudl-node-sales/image-16.webp',
      '/posters/campaign-strategy/hudl-node-sales/image-17.webp',
      '/posters/campaign-strategy/hudl-node-sales/image-18.webp',
      '/posters/campaign-strategy/hudl-node-sales/image-19.webp',
      '/posters/campaign-strategy/hudl-node-sales/image-20.webp',
    ],
  },
  {
    id: 'huddle-meet-features',
    about:
      "Huddle01 Meet is a video meeting/audio spaces app built on Huddle01's Network. Every few months we had a feature upgrade or launch to be marketed on socials.",
    role: ['Campaign Strategy', 'Social Media'],
    metrics: ['600M+ Minutes', '160K+ Users', '80K+ App downloads', '250+ Paid Users'],
    content: [
      'Worked with the Product team to ideate on key feature launches including Audio Spaces, infrastructure upgrade to 10K participants, personal dashboard and many other mini upgrades.',
      'Ran ongoing feature drops and announcements across X and Discord.',
      'Led comms for key launches: Audio Spaces, infra upgrade to 10K participants, personal dashboard.',
      'Worked with the design team to create launch videos, social media assets, infographics, and other pieces of content to generate awareness and attract new users',
    ],
    display: [
      '/posters/campaign-strategy/huddle-meet/image.webp',
      '1753060771917971495',
      '/posters/campaign-strategy/huddle-meet/image-1.webp',
      '/posters/campaign-strategy/huddle-meet/image-2.webp',
      '/posters/campaign-strategy/huddle-meet/image-3.webp',
      '/posters/campaign-strategy/huddle-meet/image-4.webp',
      '1753060764200698198',
      '/posters/campaign-strategy/huddle-meet/image-13.webp',
      '/posters/campaign-strategy/huddle-meet/image-5.webp',
      '1679516249997582336',
      '/posters/campaign-strategy/huddle-meet/image-6.webp',
      '/posters/campaign-strategy/huddle-meet/image-7.webp',
      '1778363153019007062',
      '/posters/campaign-strategy/huddle-meet/image-8.webp',
      '1678075720130781184',
      '/posters/campaign-strategy/huddle-meet/image-9.webp',
      '/posters/campaign-strategy/huddle-meet/image-12.webp',
      '1808515044583317925',
      '/posters/campaign-strategy/huddle-meet/image-10.webp',
      '/posters/campaign-strategy/huddle-meet/image-11.webp',
    ],
  },
  {
    id: 'social-media',
    about: 'Creating the right mix of relatability, awareness and visual gratification',
    display: [
      '/posters/social-media/image.webp',
      '/posters/social-media/image-1.webp',
      '/posters/social-media/image-2.webp',
      '/posters/social-media/image-3.webp',
      '/posters/social-media/image-4.webp',
      '/posters/social-media/image-5.webp',
      '/posters/social-media/image-6.webp',
      '/posters/social-media/image-7.webp',
      '/posters/social-media/image-8.webp',
      '/posters/social-media/image-9.webp',
      '/posters/social-media/image-10.webp',
      '/posters/social-media/image-11.webp',
      '/posters/social-media/image-12.webp',
      '/posters/social-media/image-13.webp',
      '/posters/social-media/image-14.webp',
      '/posters/social-media/image-15.webp',
      '/posters/social-media/image-16.webp',
      '1920137669688062045',
      '/posters/social-media/image-17.webp',
      '/posters/social-media/image-18.webp',
      '/posters/social-media/image-19.webp',
      '/posters/social-media/image-20.webp',
      '/posters/social-media/image-21.webp',
      '1919143131414507788',
      '/posters/social-media/image-22.webp',
      '/posters/social-media/image-23.webp',
      '/posters/social-media/image-24.webp',
      '1757691478267371657',
    ],
  },
  {
    id: 'long-form',
    about: 'Detailed blogs, threads and guides',
    display: [
      '/posters/long-form/image-5.webp',
      '/posters/long-form/image.webp',
      '1913159352371781942',
      '/posters/long-form/image-3.webp',
      '1931777970424942716',
      '1924530097790583265',
      '/posters/long-form/image-4.webp',
      '1813239392929976682',
      '1917582909847863671',
      '/posters/long-form/image-2.webp',
      '1925959589192716500',
      '1881688238806745575',
      '/posters/long-form/image-1.webp',
    ],
  },
];
